# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
# sudo: required

# env:
#   global:
#     - PKG_LIBS = "-llapack"
#     - PKG_CXXFLAGS = "-std=c++11"
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - libglu1-mesa-dev
#       - libgsl0-dev
